// 학습 마라톤 체크포인트 데이터

import type { MarathonCheckpoint } from "@/types";

/** 마라톤 체크포인트 (0~42.195km) */
export const marathonCheckpoints: MarathonCheckpoint[] = [
  {
    id: "start",
    km: 0,
    label: "출발! 투자성향 알아보기",
    type: "milestone",
    linkedRoute: "/onboarding",
    description: "투자성향 테스트를 완료하고 나만의 학습 경로를 설정하세요.",
    completionCheck: "onboarding-complete",
  },
  {
    id: "lesson-basics",
    km: 3,
    label: "주식이란 무엇인가?",
    type: "lesson",
    linkedRoute: "/courses/stock-basics/what-is-stock",
    description: "주식의 기본 개념을 배웁니다.",
    completionCheck: "lesson-what-is-stock",
  },
  {
    id: "lesson-market",
    km: 6,
    label: "시장 구조 이해",
    type: "lesson",
    linkedRoute: "/courses/stock-basics/market-structure",
    description: "주식 시장이 어떻게 운영되는지 배웁니다.",
    completionCheck: "lesson-market-structure",
  },
  {
    id: "glossary-10",
    km: 8,
    label: "용어 10개 저장",
    type: "practice",
    linkedRoute: "/glossary",
    description: "모르는 용어를 단어장에 10개 이상 저장하세요.",
    completionCheck: "vocabulary-10",
  },
  {
    id: "quiz-first",
    km: 10,
    label: "첫 퀴즈 통과",
    type: "quiz",
    linkedRoute: "/quiz",
    description: "학습한 내용을 퀴즈로 확인해보세요.",
    completionCheck: "quiz-first",
  },
  {
    id: "milestone-10k",
    km: 10,
    label: "10km 돌파!",
    type: "milestone",
    linkedRoute: "/marathon",
    description: "기초 학습을 마쳤습니다. 이제 차트를 배워볼 차례!",
    completionCheck: "always", // 10km 이전 체크포인트 모두 완료 시
  },
  {
    id: "chart-first",
    km: 14,
    label: "차트 뷰어 첫 사용",
    type: "practice",
    linkedRoute: "/chart",
    description: "캔들차트를 직접 확인하며 차트 읽기를 연습하세요.",
    completionCheck: "chart-visited",
  },
  {
    id: "technical-ma",
    km: 17,
    label: "이동평균선 학습",
    type: "lesson",
    linkedRoute: "/technical",
    description: "이동평균선의 개념과 활용법을 배웁니다.",
    completionCheck: "technical-visited",
  },
  {
    id: "pattern-3",
    km: 21,
    label: "패턴 게임 3개 정답",
    type: "quiz",
    linkedRoute: "/pattern-game",
    description: "차트 패턴을 보고 빠르게 판단하는 연습을 하세요.",
    completionCheck: "pattern-3-correct",
  },
  {
    id: "milestone-half",
    km: 21.1,
    label: "하프 마라톤 완주!",
    type: "milestone",
    linkedRoute: "/marathon",
    description: "절반을 달려왔습니다! 이제 실전으로 가볼까요?",
    completionCheck: "always",
  },
  {
    id: "etf-learn",
    km: 24,
    label: "ETF 기초 학습",
    type: "lesson",
    linkedRoute: "/etf",
    description: "ETF의 개념과 종류를 학습합니다.",
    completionCheck: "etf-visited",
  },
  {
    id: "sentiment-check",
    km: 27,
    label: "시장 심리 분석",
    type: "practice",
    linkedRoute: "/sentiment",
    description: "공포/탐욕 지수를 확인하고 시장 심리를 읽어보세요.",
    completionCheck: "sentiment-visited",
  },
  {
    id: "trading-first",
    km: 30,
    label: "모의투자 첫 거래",
    type: "practice",
    linkedRoute: "/trading",
    description: "가상 자금으로 첫 번째 매매를 실행해보세요!",
    completionCheck: "first-trade",
  },
  {
    id: "fundamental-read",
    km: 33,
    label: "재무제표 분석",
    type: "lesson",
    linkedRoute: "/fundamental",
    description: "삼성전자와 애플의 재무제표를 비교 분석해보세요.",
    completionCheck: "fundamental-visited",
  },
  {
    id: "valuation-calc",
    km: 36,
    label: "밸류에이션 계산",
    type: "practice",
    linkedRoute: "/fundamental/valuation",
    description: "PER, PBR, DCF 모델로 적정 주가를 계산해보세요.",
    completionCheck: "valuation-visited",
  },
  {
    id: "journal-5",
    km: 39,
    label: "투자 일지 5개 작성",
    type: "practice",
    linkedRoute: "/journal",
    description: "매매를 복기하고 교훈을 기록하는 습관을 만드세요.",
    completionCheck: "journal-5",
  },
  {
    id: "milestone-finish",
    km: 42.195,
    label: "풀 마라톤 완주!",
    type: "milestone",
    linkedRoute: "/profile",
    description: "축하합니다! 투자 학습 마라톤을 완주했습니다!",
    completionCheck: "all-complete",
  },
];

/** 총 체크포인트 수 (마일스톤 제외) */
export const totalActionCheckpoints = marathonCheckpoints.filter(
  (cp) => cp.type !== "milestone"
).length;
