import type { GlossaryTerm } from "@/types";

// 기본 용어
export const basicTerms: GlossaryTerm[] = [
  {
    id: "stock",
    termKo: "주식",
    termEn: "Stock / Share",
    definition: "기업의 소유권을 나타내는 증서. 주식을 보유하면 해당 기업의 일부를 소유하게 됩니다.",
    example: "삼성전자 주식 100주를 보유하면, 삼성전자의 아주 작은 일부를 소유하는 것입니다.",
    category: "기본",
  },
  {
    id: "ipo",
    termKo: "기업공개 (IPO)",
    termEn: "Initial Public Offering",
    definition: "비상장 기업이 처음으로 주식시장에 상장하여 일반 투자자에게 주식을 판매하는 것.",
    example: "쿠팡이 2021년 뉴욕증권거래소에 IPO하여 상장했습니다.",
    category: "기본",
  },
  {
    id: "dividend",
    termKo: "배당금",
    termEn: "Dividend",
    definition: "기업이 이익의 일부를 주주에게 분배하는 것. 현금배당과 주식배당이 있습니다.",
    example: "삼성전자가 주당 1,444원의 배당금을 지급하면, 100주 보유 시 144,400원을 받습니다.",
    category: "기본",
  },
  {
    id: "market-cap",
    termKo: "시가총액",
    termEn: "Market Capitalization",
    definition: "주가 × 발행주식수. 기업의 시장 가치를 나타내는 지표입니다.",
    example: "주가 70,000원 × 발행주식수 60억주 = 시가총액 약 420조원",
    category: "기본",
  },
  {
    id: "bull-market",
    termKo: "강세장 (불마켓)",
    termEn: "Bull Market",
    definition: "주가가 지속적으로 상승하는 시장 상태. 일반적으로 20% 이상 상승 시 강세장으로 봅니다.",
    category: "기본",
  },
  {
    id: "bear-market",
    termKo: "약세장 (베어마켓)",
    termEn: "Bear Market",
    definition: "주가가 지속적으로 하락하는 시장 상태. 일반적으로 고점 대비 20% 이상 하락 시 약세장으로 봅니다.",
    category: "기본",
  },
  {
    id: "blue-chip",
    termKo: "우량주 (블루칩)",
    termEn: "Blue Chip",
    definition: "재무상태가 건전하고 안정적인 수익을 내는 대형 기업의 주식.",
    example: "삼성전자, 애플, 마이크로소프트 등이 대표적인 블루칩 종목입니다.",
    category: "기본",
  },
  {
    id: "volume",
    termKo: "거래량",
    termEn: "Volume",
    definition: "일정 기간 동안 거래된 주식의 수. 시장의 관심도와 유동성을 나타냅니다.",
    example: "삼성전자 하루 거래량이 1000만주라면, 그날 1000만주가 사고팔린 것입니다.",
    category: "기본",
  },
  {
    id: "portfolio",
    termKo: "포트폴리오",
    termEn: "Portfolio",
    definition: "투자자가 보유한 다양한 투자자산(주식, 채권, 부동산 등)의 조합.",
    category: "기본",
  },
  {
    id: "liquidity",
    termKo: "유동성",
    termEn: "Liquidity",
    definition: "자산을 가격 변동 없이 빠르게 현금으로 전환할 수 있는 정도.",
    category: "기본",
  },
  // ===== 신규 용어 =====
  {
    id: "market-price",
    termKo: "시가/종가/고가/저가",
    termEn: "Market Price",
    definition: "주식 거래에서 사용되는 4가지 기본 가격. 시가(장 시작 가격), 종가(장 마감 가격), 고가(당일 최고가), 저가(당일 최저가)를 의미합니다.",
    example: "삼성전자 시가 71,000원, 고가 72,500원, 저가 70,500원, 종가 72,000원으로 마감했습니다.",
    category: "기본",
  },
  {
    id: "bid-ask",
    termKo: "호가",
    termEn: "Bid/Ask Price",
    definition: "매수자가 사려는 가격(매수호가)과 매도자가 팔려는 가격(매도호가). 매수호가와 매도호가의 차이를 스프레드라고 합니다.",
    example: "매수호가 70,000원, 매도호가 70,100원이면 스프레드는 100원입니다. 스프레드가 좁을수록 유동성이 높습니다.",
    category: "기본",
  },
  {
    id: "return-rate",
    termKo: "수익률",
    termEn: "Return/Yield",
    definition: "투자 원금 대비 이익의 비율. (매도가 - 매수가) ÷ 매수가 × 100으로 계산합니다.",
    example: "50,000원에 산 주식을 60,000원에 팔면 수익률은 (60,000-50,000) ÷ 50,000 × 100 = 20%입니다.",
    category: "기본",
  },
  {
    id: "benchmark",
    termKo: "벤치마크",
    termEn: "Benchmark",
    definition: "투자 성과를 비교하기 위한 기준 지수. 내 포트폴리오의 수익률을 벤치마크와 비교하여 성과를 평가합니다.",
    example: "한국 주식 펀드의 벤치마크는 KOSPI, 미국 대형주 펀드의 벤치마크는 S&P 500이 일반적입니다.",
    category: "기본",
  },
  {
    id: "rebalancing",
    termKo: "리밸런싱",
    termEn: "Rebalancing",
    definition: "포트폴리오의 자산 배분 비율을 원래 목표로 되돌리는 것. 주기적으로 비중이 달라진 자산을 매매하여 조정합니다.",
    example: "주식 60%, 채권 40% 목표인데 주가 상승으로 주식 70%가 되었다면, 주식 일부를 팔고 채권을 사서 원래 비율로 조정합니다.",
    category: "기본",
  },
];
