import type { GlossaryTerm } from "@/types";

// ETF/펀드 용어
export const etfFundTerms: GlossaryTerm[] = [
  {
    id: "index-fund",
    termKo: "인덱스 펀드",
    termEn: "Index Fund",
    definition: "특정 시장 지수를 그대로 추종하도록 설계된 펀드. 낮은 보수와 안정적인 수익이 장점입니다.",
    example: "미국 뱅가드의 S&P 500 인덱스 펀드가 대표적. 보수율 0.03%로 매우 저렴합니다.",
    category: "ETF/펀드",
  },
  {
    id: "active-fund",
    termKo: "액티브 펀드",
    termEn: "Active Fund",
    definition: "펀드 매니저가 시장을 이기기 위해 적극적으로 종목을 선별하는 펀드. 패시브 펀드보다 보수가 높습니다.",
    example: "피델리티 마젤란 펀드, 한국의 각종 주식형 펀드 등이 있습니다. 장기적으로 인덱스 펀드를 이기기 어렵다는 통계가 많습니다.",
    category: "ETF/펀드",
  },
  {
    id: "passive-fund",
    termKo: "패시브 펀드",
    termEn: "Passive Fund",
    definition: "시장 지수를 추종하며 최소한의 매매만 하는 펀드. 인덱스 펀드와 유사한 개념으로, 낮은 비용이 특징입니다.",
    example: "KODEX 200, TIGER 미국S&P500 등 대부분의 ETF가 패시브 전략을 따릅니다.",
    category: "ETF/펀드",
  },
  {
    id: "ter",
    termKo: "총보수비율 (TER)",
    termEn: "Total Expense Ratio",
    definition: "펀드 운용에 드는 총 비용의 비율. 운용보수, 판매보수, 수탁보수 등이 포함되며, 낮을수록 투자자에게 유리합니다.",
    example: "TER 0.05%인 ETF는 1,000만원 투자 시 연간 5,000원, TER 1.5%인 펀드는 15만원의 비용이 발생합니다.",
    category: "ETF/펀드",
  },
  {
    id: "tracking-error",
    termKo: "추적오차",
    termEn: "Tracking Error",
    definition: "ETF의 수익률과 추종 지수의 수익률 차이. 낮을수록 지수를 잘 추종하는 ETF입니다.",
    example: "KODEX 200의 추적오차가 0.1%라면, 코스피200 지수와 거의 동일하게 움직인다는 뜻입니다.",
    category: "ETF/펀드",
  },
  {
    id: "nav",
    termKo: "순자산가치 (NAV)",
    termEn: "Net Asset Value",
    definition: "펀드가 보유한 자산의 총 가치에서 부채를 뺀 금액. ETF의 경우 NAV와 시장가격의 괴리를 확인하는 것이 중요합니다.",
    example: "NAV가 50,000원인데 ETF 시장가가 50,500원이면 500원의 프리미엄이 붙어 있다는 뜻입니다.",
    category: "ETF/펀드",
  },
  {
    id: "leveraged-etf",
    termKo: "레버리지 ETF",
    termEn: "Leveraged ETF",
    definition: "기초 지수 수익률의 2배 또는 3배를 추종하는 ETF. 단기 트레이딩용으로 설계되어 장기 보유에는 부적합합니다.",
    example: "KODEX 레버리지 ETF는 코스피200의 일일 수익률 2배를 추종합니다. 지수가 1% 오르면 약 2% 상승합니다.",
    category: "ETF/펀드",
  },
  {
    id: "inverse-etf",
    termKo: "인버스 ETF",
    termEn: "Inverse ETF",
    definition: "기초 지수와 반대 방향으로 움직이는 ETF. 하락장에서 수익을 얻을 수 있는 헤지 수단입니다.",
    example: "KODEX 인버스 ETF는 코스피200이 1% 하락하면 약 1% 상승합니다. 하락장 예상 시 단기 방어 수단으로 활용합니다.",
    category: "ETF/펀드",
  },
  {
    id: "dividend-etf",
    termKo: "배당 ETF",
    termEn: "Dividend ETF",
    definition: "높은 배당 수익률을 제공하는 종목으로 구성된 ETF. 안정적인 인컴(현금흐름)을 추구하는 투자자에게 적합합니다.",
    example: "미국 SCHD(슈왑 미국 배당주 ETF), 한국 TIGER 배당성장 ETF 등이 대표적입니다.",
    category: "ETF/펀드",
  },
  {
    id: "sector-etf",
    termKo: "섹터 ETF",
    termEn: "Sector ETF",
    definition: "특정 산업 분야(반도체, 헬스케어, 금융 등)에 집중 투자하는 ETF. 개별 종목 리스크를 줄이면서 특정 섹터에 투자할 수 있습니다.",
    example: "TIGER 반도체 ETF, 미국 XLF(금융 섹터 ETF), XLK(기술 섹터 ETF) 등이 있습니다.",
    category: "ETF/펀드",
  },
  {
    id: "bond-etf",
    termKo: "채권 ETF",
    termEn: "Bond ETF",
    definition: "국채, 회사채 등 채권에 투자하는 ETF. 주식보다 낮은 변동성으로 포트폴리오의 안정성을 높여줍니다.",
    example: "미국 TLT(20년 이상 미국 국채 ETF), 한국 KODEX 국고채10년 ETF 등이 있습니다. 금리 하락 시 채권 가격이 상승합니다.",
    category: "ETF/펀드",
  },
  {
    id: "reit",
    termKo: "리츠 (REIT)",
    termEn: "Real Estate Investment Trust",
    definition: "부동산에 투자하여 임대수익과 매각차익을 배분하는 펀드 또는 회사. 소액으로 부동산에 간접 투자할 수 있습니다.",
    example: "미국 리얼티인컴(O), 한국 맥쿼리인프라(088980) 등이 대표적. 이익의 90% 이상을 배당으로 지급해야 합니다.",
    category: "ETF/펀드",
  },
  {
    id: "fund-of-funds",
    termKo: "펀드오브펀드",
    termEn: "Fund of Funds",
    definition: "다른 펀드에 투자하는 펀드. 여러 펀드에 분산투자하여 추가적인 분산효과를 얻을 수 있지만, 이중 보수가 발생합니다.",
    example: "TDF(타겟데이트펀드)가 대표적인 펀드오브펀드로, 국내외 주식·채권 펀드에 분산 투자하며 은퇴 시점에 맞춰 자산배분을 조절합니다.",
    category: "ETF/펀드",
  },
];
