import type { GlossaryTerm } from "@/types";

// 기본적분석 용어
export const fundamentalTerms: GlossaryTerm[] = [
  {
    id: "per",
    termKo: "PER (주가수익비율)",
    termEn: "Price to Earnings Ratio",
    definition: "주가 ÷ 주당순이익(EPS). 주가가 이익의 몇 배인지 나타내는 지표. 낮을수록 저평가 가능성.",
    example: "주가 50,000원, EPS 5,000원이면 PER = 10배. '이익의 10년치 가격'이라고 해석 가능.",
    category: "기본적분석",
  },
  {
    id: "pbr",
    termKo: "PBR (주가순자산비율)",
    termEn: "Price to Book Ratio",
    definition: "주가 ÷ 주당순자산(BPS). 주가가 순자산의 몇 배인지 나타내는 지표.",
    example: "PBR이 1 미만이면, 시장에서 기업의 순자산보다 낮게 평가하는 것입니다.",
    category: "기본적분석",
  },
  {
    id: "roe",
    termKo: "ROE (자기자본이익률)",
    termEn: "Return on Equity",
    definition: "순이익 ÷ 자기자본 × 100. 주주가 투자한 돈으로 얼마나 이익을 냈는지 나타내는 지표.",
    example: "ROE 15%는 주주의 100원으로 15원의 이익을 낸다는 뜻.",
    category: "기본적분석",
  },
  {
    id: "eps",
    termKo: "EPS (주당순이익)",
    termEn: "Earnings Per Share",
    definition: "순이익 ÷ 발행주식수. 주식 1주당 얼마의 이익을 냈는지 나타내는 지표.",
    category: "기본적분석",
  },
  {
    id: "revenue",
    termKo: "매출액",
    termEn: "Revenue / Sales",
    definition: "기업이 제품이나 서비스를 판매하여 얻은 총 수입. 손익계산서의 최상단 항목.",
    category: "기본적분석",
  },
  {
    id: "operating-income",
    termKo: "영업이익",
    termEn: "Operating Income",
    definition: "매출에서 영업비용(원가, 판관비)을 뺀 이익. 기업의 본업 수익성을 나타냄.",
    category: "기본적분석",
  },
  {
    id: "net-income",
    termKo: "순이익",
    termEn: "Net Income",
    definition: "모든 수익에서 모든 비용(세금, 이자 포함)을 차감한 최종 이익.",
    category: "기본적분석",
  },
  {
    id: "debt-ratio",
    termKo: "부채비율",
    termEn: "Debt to Equity Ratio",
    definition: "총부채 ÷ 자기자본 × 100. 기업의 재무 건전성을 나타내는 지표. 일반적으로 200% 이하가 안전.",
    category: "기본적분석",
  },
  {
    id: "free-cash-flow",
    termKo: "잉여현금흐름 (FCF)",
    termEn: "Free Cash Flow",
    definition: "영업활동현금흐름에서 자본적 지출(CAPEX)을 뺀 금액. 기업이 자유롭게 사용할 수 있는 현금.",
    category: "기본적분석",
  },
  {
    id: "dcf",
    termKo: "DCF (할인현금흐름)",
    termEn: "Discounted Cash Flow",
    definition: "미래 현금흐름을 현재 가치로 환산하여 기업의 내재가치를 구하는 밸류에이션 방법.",
    category: "기본적분석",
  },
  // ===== 신규 용어 =====
  {
    id: "psr",
    termKo: "PSR (주가매출비율)",
    termEn: "Price to Sales Ratio",
    definition: "시가총액 ÷ 매출액. 주가가 매출의 몇 배인지 나타내는 지표. 아직 이익이 없는 성장주 평가에 유용합니다.",
    example: "적자 기업이라 PER 계산이 불가할 때, PSR 5배라면 매출의 5배 가치로 평가된다는 뜻입니다. 테슬라 초기에 PSR로 평가했습니다.",
    category: "기본적분석",
  },
  {
    id: "ev-ebitda",
    termKo: "EV/EBITDA",
    termEn: "Enterprise Value to EBITDA",
    definition: "기업가치(EV) ÷ EBITDA. 부채를 고려한 밸류에이션 지표로, PER보다 자본구조에 덜 영향을 받습니다.",
    example: "EV/EBITDA가 8배라면, 현재 EBITDA를 기준으로 기업 인수 비용을 8년 만에 회수할 수 있다는 의미입니다.",
    category: "기본적분석",
  },
  {
    id: "ebitda",
    termKo: "EBITDA",
    termEn: "EBITDA",
    definition: "이자(Interest)·세금(Tax)·감가상각(Depreciation)·무형자산상각(Amortization) 전 이익. 영업활동의 현금 창출 능력을 나타냅니다.",
    example: "영업이익 100억원, 감가상각비 30억원이면 EBITDA는 약 130억원입니다. 기업 간 수익성 비교에 유용합니다.",
    category: "기본적분석",
  },
  {
    id: "depreciation",
    termKo: "감가상각",
    termEn: "Depreciation",
    definition: "유형자산(건물, 설비 등)의 가치를 사용 기간에 걸쳐 비용으로 인식하는 것. 실제 현금 유출 없이 비용으로 처리됩니다.",
    example: "1억원짜리 기계를 10년 정액법으로 감가상각하면, 매년 1,000만원을 비용으로 인식합니다.",
    category: "기본적분석",
  },
  {
    id: "capex",
    termKo: "자본적지출 (CAPEX)",
    termEn: "Capital Expenditure",
    definition: "건물·설비·장비 등 유형자산에 투자하는 비용. 미래 수익 창출을 위한 장기 투자입니다.",
    example: "삼성전자의 반도체 공장 건설 투자, TSMC의 첨단 팹 건설 비용이 대표적인 CAPEX입니다.",
    category: "기본적분석",
  },
  {
    id: "gross-margin",
    termKo: "매출총이익률",
    termEn: "Gross Margin",
    definition: "(매출액 - 매출원가) ÷ 매출액 × 100. 제품이나 서비스의 기본적인 수익성을 나타내는 지표입니다.",
    example: "애플의 매출총이익률은 약 45%로, 100원 매출에 45원이 이익입니다. 소프트웨어 기업은 70~80% 이상도 가능합니다.",
    category: "기본적분석",
  },
  {
    id: "operating-margin",
    termKo: "영업이익률",
    termEn: "Operating Margin",
    definition: "영업이익 ÷ 매출액 × 100. 기업의 본업 수익성 효율을 나타냅니다. 판관비까지 고려한 실질적 수익성입니다.",
    example: "삼성전자의 영업이익률이 15%라면, 매출 100원당 본업에서 15원의 이익을 낸다는 뜻입니다.",
    category: "기본적분석",
  },
  {
    id: "payout-ratio",
    termKo: "배당성향",
    termEn: "Payout Ratio",
    definition: "순이익 중 배당금으로 지급하는 비율. 배당금 ÷ 순이익 × 100으로 계산하며, 30~50%가 일반적입니다.",
    example: "순이익 1,000억원, 배당금 총 400억원이면 배당성향 40%입니다. 한국 기업은 미국 대비 배당성향이 낮은 편입니다.",
    category: "기본적분석",
  },
];
