import type { GlossaryTerm } from "@/types";

// 투자전략 용어
export const investmentTerms: GlossaryTerm[] = [
  {
    id: "value-investing",
    termKo: "가치투자",
    termEn: "Value Investing",
    definition: "내재가치보다 낮은 가격에 거래되는 주식을 매수하여 장기적으로 가치가 실현되기를 기다리는 전략입니다.",
    example: "워렌 버핏의 대표 전략. PER, PBR이 낮고 재무가 건전한 기업을 저가에 매수하여 장기 보유합니다.",
    category: "투자전략",
  },
  {
    id: "growth-investing",
    termKo: "성장투자",
    termEn: "Growth Investing",
    definition: "높은 매출/이익 성장이 기대되는 기업에 투자하는 전략. 현재 밸류에이션이 높더라도 미래 성장에 베팅합니다.",
    example: "테슬라, 아마존 초기 투자가 대표적. 매출 성장률이 높고, 시장을 지배할 가능성이 있는 기업을 선별합니다.",
    category: "투자전략",
  },
  {
    id: "momentum-investing",
    termKo: "모멘텀 투자",
    termEn: "Momentum Investing",
    definition: "상승 추세의 주식을 매수하고 하락 추세의 주식을 매도하는 전략. '추세는 지속된다'는 가정에 기반합니다.",
    example: "52주 신고가를 갱신하는 종목에 진입하거나, 상대강도가 높은 종목군에 집중 투자하는 방법이 있습니다.",
    category: "투자전략",
  },
  {
    id: "index-investing",
    termKo: "인덱스 투자",
    termEn: "Index Investing",
    definition: "S&P 500 등 시장 지수를 추종하는 펀드나 ETF에 투자하는 전략. 장기적으로 대부분의 액티브 펀드 수익률을 능가합니다.",
    example: "매달 S&P 500 ETF에 일정 금액을 투자하는 것만으로도 연평균 약 10%의 수익률을 기대할 수 있습니다.",
    category: "투자전략",
  },
  {
    id: "dca",
    termKo: "적립식투자 (DCA)",
    termEn: "Dollar-Cost Averaging",
    definition: "정기적으로 일정 금액을 투자하여 매수 단가를 평균화하는 전략. 시장 타이밍 위험을 줄여줍니다.",
    example: "매월 50만원씩 KODEX 200 ETF를 매수하면, 가격이 높을 때 적게, 낮을 때 많이 사게 되어 평균 매수가가 낮아집니다.",
    category: "투자전략",
  },
  {
    id: "stop-loss",
    termKo: "손절매",
    termEn: "Stop Loss",
    definition: "미리 정한 손실 한도에 도달하면 포지션을 정리하는 것. 리스크 관리의 핵심 전략입니다.",
    example: "매수가 대비 -7% 손절 규칙을 세우면, 10만원에 산 주식이 93,000원이 되면 자동으로 매도합니다.",
    category: "투자전략",
  },
  {
    id: "take-profit",
    termKo: "익절",
    termEn: "Take Profit",
    definition: "미리 정한 수익 목표에 도달하면 포지션을 정리하여 이익을 확정하는 것. 탐욕을 억제하고 안정적 수익을 추구합니다.",
    example: "+20% 익절 규칙을 세우면, 10만원에 산 주식이 12만원이 되었을 때 매도하여 이익을 실현합니다.",
    category: "투자전략",
  },
  {
    id: "averaging-down",
    termKo: "물타기/불타기",
    termEn: "Averaging Down/Up",
    definition: "물타기는 하락 시 추가 매수로 평균매수가를 낮추는 것, 불타기는 상승 시 추가 매수로 수익을 극대화하는 것입니다. 양날의 검과 같은 전략입니다.",
    example: "10만원에 100주 매수 후 8만원에 100주 추가 매수하면 평균매수가 9만원. 반등 시 유리하지만 추가 하락 시 손실이 커집니다.",
    category: "투자전략",
  },
  {
    id: "scaled-order",
    termKo: "분할매수/분할매도",
    termEn: "Scaled Order",
    definition: "한 번에 전량을 거래하지 않고 여러 번에 나누어 거래하는 전략. 타이밍 위험을 분산시킵니다.",
    example: "1,000만원 투자 시 한 번에 매수하지 않고, 3회(400만/300만/300만원)에 나누어 매수하여 평균 매수가를 관리합니다.",
    category: "투자전략",
  },
  {
    id: "contrarian",
    termKo: "역발상 투자",
    termEn: "Contrarian Investing",
    definition: "시장 다수의 의견과 반대로 투자하는 전략. 과도한 비관에 매수하고 과도한 낙관에 매도합니다.",
    example: "'공포에 사고 탐욕에 팔아라' - 워렌 버핏. 2020년 코로나 폭락 시 매수한 투자자들이 큰 수익을 얻었습니다.",
    category: "투자전략",
  },
  {
    id: "buy-and-hold",
    termKo: "바이앤홀드",
    termEn: "Buy and Hold",
    definition: "주식을 매수한 후 장기간 보유하는 전략. 단기 변동에 흔들리지 않고 기업의 장기 성장에 투자합니다.",
    example: "워렌 버핏: '10년 보유할 주식이 아니면 10분도 보유하지 마라.' 코카콜라 주식을 30년 이상 보유한 것이 대표적 사례입니다.",
    category: "투자전략",
  },
  {
    id: "theme-investing",
    termKo: "테마투자",
    termEn: "Theme Investing",
    definition: "특정 산업 트렌드나 테마(AI, 전기차, 바이오 등)에 집중 투자하는 전략. 높은 수익 가능성이 있지만 테마 소멸 위험도 있습니다.",
    example: "2023~2024년 AI 테마로 엔비디아, AMD 등 반도체주가 큰 상승을 보였습니다. 한국에서는 2차전지 테마가 인기를 끌었습니다.",
    category: "투자전략",
  },
];
