import type { GlossaryTerm } from "@/types";

// 시장구조 용어
export const marketStructureTerms: GlossaryTerm[] = [
  {
    id: "kospi",
    termKo: "코스피",
    termEn: "KOSPI",
    definition: "한국거래소의 유가증권시장. 대형 우량주 중심의 한국 대표 주식시장.",
    category: "시장구조",
  },
  {
    id: "kosdaq",
    termKo: "코스닥",
    termEn: "KOSDAQ",
    definition: "한국의 중소·벤처기업 중심 주식시장. 미국 나스닥을 모델로 만들어짐.",
    category: "시장구조",
  },
  {
    id: "nyse",
    termKo: "뉴욕증권거래소",
    termEn: "NYSE (New York Stock Exchange)",
    definition: "세계 최대 규모의 증권거래소. 미국 대형주 중심.",
    category: "시장구조",
  },
  {
    id: "nasdaq",
    termKo: "나스닥",
    termEn: "NASDAQ",
    definition: "미국의 전자 증권거래소. 기술주 중심으로 애플, 구글, 테슬라 등이 상장.",
    category: "시장구조",
  },
  {
    id: "sp500",
    termKo: "S&P 500",
    termEn: "S&P 500 Index",
    definition: "미국 대형주 500개로 구성된 주가지수. 미국 주식시장의 대표 벤치마크.",
    category: "시장구조",
  },
  {
    id: "etf",
    termKo: "ETF (상장지수펀드)",
    termEn: "Exchange Traded Fund",
    definition: "특정 지수나 자산을 추종하도록 설계된 펀드로, 주식처럼 거래소에서 거래 가능.",
    example: "KODEX 200 ETF는 코스피 200 지수를 추종합니다.",
    category: "시장구조",
  },
  {
    id: "short-selling",
    termKo: "공매도",
    termEn: "Short Selling",
    definition: "주식을 빌려서 먼저 팔고, 나중에 더 낮은 가격에 사서 갚는 투자 전략. 하락장에서 수익 가능.",
    category: "시장구조",
  },
  {
    id: "circuit-breaker",
    termKo: "서킷브레이커",
    termEn: "Circuit Breaker",
    definition: "주가가 급락할 때 시장 거래를 일시 중단하는 제도. 투자자 보호와 시장 안정을 위함.",
    category: "시장구조",
  },
  {
    id: "margin-trading",
    termKo: "신용거래 (마진거래)",
    termEn: "Margin Trading",
    definition: "증권사에서 돈을 빌려 주식을 매수하는 것. 레버리지 효과가 있지만 위험도 높음.",
    category: "시장구조",
  },
  {
    id: "after-hours",
    termKo: "시간외 거래",
    termEn: "After-Hours Trading",
    definition: "정규 거래 시간 이후에 이루어지는 주식 거래. 유동성이 낮아 가격 변동이 클 수 있음.",
    category: "시장구조",
  },
  // ===== 신규 용어 =====
  {
    id: "dow-jones",
    termKo: "다우존스",
    termEn: "Dow Jones Industrial Average",
    definition: "미국의 대표적 주가지수로 30개 우량 대기업으로 구성됩니다. 가격가중방식으로 계산되어, 주가가 높은 종목이 지수에 더 큰 영향을 미칩니다.",
    example: "애플, 마이크로소프트, 골드만삭스 등 미국을 대표하는 30개 기업으로 구성되어 있으며, 1896년부터 산출된 가장 오래된 주가지수입니다.",
    category: "시장구조",
  },
  {
    id: "pre-after-market",
    termKo: "프리마켓/애프터마켓",
    termEn: "Pre-Market/After-Market Trading",
    definition: "정규 거래 시간 전후의 연장 거래 시간. 미국 시장에서 주로 활용되며, 실적 발표 등에 즉시 반응할 수 있습니다.",
    example: "미국 프리마켓은 오전 4시~9시30분(ET), 애프터마켓은 오후 4시~8시(ET)에 거래됩니다. 한국 시간으로는 밤~새벽 시간대입니다.",
    category: "시장구조",
  },
  {
    id: "settlement-date",
    termKo: "결제일",
    termEn: "Settlement Date",
    definition: "주식 거래 후 실제 주식과 대금이 이동하는 날. 거래일(T)로부터 일정 기간 후에 결제가 완료됩니다.",
    example: "한국은 T+2(거래 후 2영업일), 미국은 T+1(거래 후 1영업일)에 결제가 이루어집니다.",
    category: "시장구조",
  },
  {
    id: "delisting",
    termKo: "상장폐지",
    termEn: "Delisting",
    definition: "주식이 거래소에서 거래 대상에서 제외되는 것. 관리종목 지정 후 일정 요건을 충족하지 못하면 진행될 수 있습니다.",
    example: "매출액 미달, 감사의견 거절, 자본잠식 등의 사유로 상장폐지가 될 수 있으며, 투자금 회수가 극히 어려워집니다.",
    category: "시장구조",
  },
  {
    id: "stock-split",
    termKo: "주식분할",
    termEn: "Stock Split",
    definition: "기존 주식을 여러 주로 분할하여 주당 가격을 낮추는 것. 시가총액은 변동 없이 주식 수만 늘어나 접근성이 높아집니다.",
    example: "애플이 4:1 주식분할을 하면 400달러 주식이 100달러 4주가 됩니다. 테슬라, 엔비디아도 주식분할을 실시한 바 있습니다.",
    category: "시장구조",
  },
];
