import type { GlossaryTerm } from "@/types";

// 기술적분석 용어
export const technicalTerms: GlossaryTerm[] = [
  {
    id: "candlestick",
    termKo: "캔들차트 (봉차트)",
    termEn: "Candlestick Chart",
    definition: "시가, 종가, 고가, 저가를 하나의 봉 모양으로 표현한 차트. 가장 널리 사용되는 주가 차트 유형.",
    category: "기술적분석",
  },
  {
    id: "moving-average",
    termKo: "이동평균선",
    termEn: "Moving Average (MA)",
    definition: "일정 기간의 주가 평균을 연결한 선. 추세의 방향과 지지/저항을 판단하는 데 사용.",
    example: "20일 이동평균선은 최근 20일간 종가의 평균을 연결한 선입니다.",
    category: "기술적분석",
  },
  {
    id: "golden-cross",
    termKo: "골든크로스",
    termEn: "Golden Cross",
    definition: "단기 이동평균선이 장기 이동평균선을 아래에서 위로 돌파하는 것. 매수 신호로 해석.",
    category: "기술적분석",
  },
  {
    id: "dead-cross",
    termKo: "데드크로스",
    termEn: "Dead Cross",
    definition: "단기 이동평균선이 장기 이동평균선을 위에서 아래로 돌파하는 것. 매도 신호로 해석.",
    category: "기술적분석",
  },
  {
    id: "rsi",
    termKo: "RSI (상대강도지수)",
    termEn: "Relative Strength Index",
    definition: "주가의 과매수/과매도 상태를 0~100으로 나타내는 지표. 70 이상은 과매수, 30 이하는 과매도.",
    category: "기술적분석",
  },
  {
    id: "macd",
    termKo: "MACD",
    termEn: "Moving Average Convergence Divergence",
    definition: "두 이동평균선의 수렴과 발산을 이용한 추세 추종 지표.",
    category: "기술적분석",
  },
  {
    id: "bollinger-bands",
    termKo: "볼린저밴드",
    termEn: "Bollinger Bands",
    definition: "이동평균선을 중심으로 상·하한 밴드를 표시한 지표. 변동성과 과매수/과매도를 판단.",
    category: "기술적분석",
  },
  {
    id: "support",
    termKo: "지지선",
    termEn: "Support Level",
    definition: "주가가 하락하다가 매수세로 인해 반등하는 가격대.",
    category: "기술적분석",
  },
  {
    id: "resistance",
    termKo: "저항선",
    termEn: "Resistance Level",
    definition: "주가가 상승하다가 매도세로 인해 하락하는 가격대.",
    category: "기술적분석",
  },
  {
    id: "trend",
    termKo: "추세",
    termEn: "Trend",
    definition: "주가가 일정 방향으로 움직이는 경향. 상승추세, 하락추세, 횡보(박스권)로 구분.",
    category: "기술적분석",
  },
  // ===== 신규 용어 =====
  {
    id: "stochastic",
    termKo: "스토캐스틱",
    termEn: "Stochastic Oscillator",
    definition: "현재 가격이 일정 기간의 가격 범위에서 어디에 위치하는지 백분율(0~100)로 나타내는 지표. %K선과 %D선으로 구성됩니다.",
    example: "%K가 80 이상이면 과매수, 20 이하이면 과매도로 판단합니다. %K가 %D를 상향 돌파하면 매수 신호입니다.",
    category: "기술적분석",
  },
  {
    id: "fibonacci",
    termKo: "피보나치 되돌림",
    termEn: "Fibonacci Retracement",
    definition: "피보나치 수열을 기반으로 주가의 되돌림 수준을 예측하는 기술적 분석 도구. 23.6%, 38.2%, 50%, 61.8% 되돌림 레벨을 사용합니다.",
    example: "주가가 10,000원에서 20,000원으로 상승 후 되돌림이 올 때, 61.8% 레벨인 13,820원 근처에서 지지를 기대할 수 있습니다.",
    category: "기술적분석",
  },
  {
    id: "ichimoku",
    termKo: "일목균형표",
    termEn: "Ichimoku Cloud",
    definition: "일본에서 개발된 기술적 분석 도구로 전환선, 기준선, 후행스팬, 선행스팬1, 선행스팬2의 5개 선으로 구성됩니다. 구름(클라우드) 영역이 지지/저항 역할을 합니다.",
    example: "주가가 구름 위에 있으면 상승 추세, 구름 아래에 있으면 하락 추세로 판단합니다.",
    category: "기술적분석",
  },
  {
    id: "elliott-wave",
    termKo: "엘리어트 파동",
    termEn: "Elliott Wave",
    definition: "주가가 5개의 상승파(충격파)와 3개의 하락파(조정파)로 움직인다는 이론. 파동의 패턴을 분석하여 미래 가격을 예측합니다.",
    example: "1-2-3-4-5 상승파 후 A-B-C 조정파가 나타나며, 3번 파동이 가장 강력한 상승을 보입니다.",
    category: "기술적분석",
  },
  {
    id: "gap",
    termKo: "갭",
    termEn: "Gap",
    definition: "전일 종가와 당일 시가 사이의 가격 차이. 상승갭(갭업)은 시가가 전일 종가보다 높게, 하락갭(갭다운)은 낮게 시작하는 것입니다.",
    example: "어닝 서프라이즈 발표 후 다음날 5% 상승갭으로 시작하는 경우가 많습니다. 갭은 보통 채워지는 경향이 있습니다.",
    category: "기술적분석",
  },
  {
    id: "divergence",
    termKo: "다이버전스",
    termEn: "Divergence",
    definition: "주가와 기술적 지표(RSI, MACD 등)가 서로 다른 방향으로 움직이는 현상. 추세 전환의 강력한 신호로 해석됩니다.",
    example: "주가는 신고가를 갱신하지만 RSI는 이전 고점보다 낮으면 '하락 다이버전스'로, 상승 추세 약화를 의미합니다.",
    category: "기술적분석",
  },
  {
    id: "disparity",
    termKo: "이격도",
    termEn: "Disparity",
    definition: "현재 주가와 이동평균선 사이의 괴리 정도를 나타내는 지표. (현재가 ÷ 이동평균) × 100으로 계산합니다.",
    example: "20일 이격도가 110이면 이동평균보다 10% 위에 있다는 뜻으로, 과매수 상태를 의미할 수 있습니다.",
    category: "기술적분석",
  },
];
